repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
-   repo: local
    hooks:
    -   id: swiftformat
        name: SwiftFormat
        entry: ./Pods/SwiftFormat/CommandLineTool/swiftformat
        language: system
        types: [swift]
    -   id: swiftlint
        name: SwiftLint
        entry: ./Pods/SwiftLint/swiftlint
        language: system
        types: [swift]